name: Auto Update Playlist

on:
  schedule:
    # বাংলাদেশ সময় দুপুর ১২টা = UTC ০৬:০০
    - cron: "0 6 * * *"
    # বাংলাদেশ সময় রাত ৮টা = UTC ১৪:০০
    - cron: "0 14 * * *"
    # বাংলাদেশ সময় রাত ১টা = UTC ১৯:০০
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      # এখানে scraper.py ফাইলটি রান হবে
      - run: python scraper.py
      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Auto Update Playlist" || exit 0
          git push
