name: Auto Update Playlist

on:
  schedule:
    # রাত ৮টা (২০:০০) - স্পোর্টস শুরু হওয়ার ঠিক আগে
    - cron: "0 14 * * *"
    # রাত ১টা (০১:০০) - কার্টুন শুরু হওয়ার ঠিক আগে
    - cron: "0 19 * * *"
    # অন্যান্য সময়গুলো ৪ ঘণ্টা পরপর আপডেট (যাতে প্লেলিস্ট সবসময় সতেজ থাকে)
    - cron: "0 0 * * *"
    - cron: "0 4 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Auto Update Playlist" || exit 0
          git push
